//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universa.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsMigrated {
            get {
                return ((bool)(this["SettingsMigrated"]));
            }
            set {
                this["SettingsMigrated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double LastChatWidth {
            get {
                return ((double)(this["LastChatWidth"]));
            }
            set {
                this["LastChatWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double LastLibraryWidth {
            get {
                return ((double)(this["LastLibraryWidth"]));
            }
            set {
                this["LastLibraryWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LibraryPath {
            get {
                return ((string)(this["LibraryPath"]));
            }
            set {
                this["LibraryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string CurrentTheme {
            get {
                return ((string)(this["CurrentTheme"]));
            }
            set {
                this["CurrentTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubsonicUrl {
            get {
                return ((string)(this["SubsonicUrl"]));
            }
            set {
                this["SubsonicUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubsonicUsername {
            get {
                return ((string)(this["SubsonicUsername"]));
            }
            set {
                this["SubsonicUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubsonicPassword {
            get {
                return ((string)(this["SubsonicPassword"]));
            }
            set {
                this["SubsonicPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubsonicName {
            get {
                return ((string)(this["SubsonicName"]));
            }
            set {
                this["SubsonicName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixUrl {
            get {
                return ((string)(this["MatrixUrl"]));
            }
            set {
                this["MatrixUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixUsername {
            get {
                return ((string)(this["MatrixUsername"]));
            }
            set {
                this["MatrixUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixPassword {
            get {
                return ((string)(this["MatrixPassword"]));
            }
            set {
                this["MatrixPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixName {
            get {
                return ((string)(this["MatrixName"]));
            }
            set {
                this["MatrixName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixAccessToken {
            get {
                return ((string)(this["MatrixAccessToken"]));
            }
            set {
                this["MatrixAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JellyfinUrl {
            get {
                return ((string)(this["JellyfinUrl"]));
            }
            set {
                this["JellyfinUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JellyfinUsername {
            get {
                return ((string)(this["JellyfinUsername"]));
            }
            set {
                this["JellyfinUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JellyfinPassword {
            get {
                return ((string)(this["JellyfinPassword"]));
            }
            set {
                this["JellyfinPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JellyfinName {
            get {
                return ((string)(this["JellyfinName"]));
            }
            set {
                this["JellyfinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JellyfinAccessToken {
            get {
                return ((string)(this["JellyfinAccessToken"]));
            }
            set {
                this["JellyfinAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#81C784")]
        public string DarkModePlayingColor {
            get {
                return ((string)(this["DarkModePlayingColor"]));
            }
            set {
                this["DarkModePlayingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#757575")]
        public string DarkModePausedColor {
            get {
                return ((string)(this["DarkModePausedColor"]));
            }
            set {
                this["DarkModePausedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CAF50")]
        public string LightModePlayingColor {
            get {
                return ((string)(this["LightModePlayingColor"]));
            }
            set {
                this["LightModePlayingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#9E9E9E")]
        public string LightModePausedColor {
            get {
                return ((string)(this["LightModePausedColor"]));
            }
            set {
                this["LightModePausedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WrapLongText {
            get {
                return ((bool)(this["WrapLongText"]));
            }
            set {
                this["WrapLongText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CachedArtists {
            get {
                return ((string)(this["CachedArtists"]));
            }
            set {
                this["CachedArtists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CachedAlbums {
            get {
                return ((string)(this["CachedAlbums"]));
            }
            set {
                this["CachedAlbums"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CachedPlaylists {
            get {
                return ((string)(this["CachedPlaylists"]));
            }
            set {
                this["CachedPlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string OpenTabs {
            get {
                return ((string)(this["OpenTabs"]));
            }
            set {
                this["OpenTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E3F2FD")]
        public string LightModePlayingTrackColor {
            get {
                return ((string)(this["LightModePlayingTrackColor"]));
            }
            set {
                this["LightModePlayingTrackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1A3B5C")]
        public string DarkModePlayingTrackColor {
            get {
                return ((string)(this["DarkModePlayingTrackColor"]));
            }
            set {
                this["DarkModePlayingTrackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF424242")]
        public string DarkModeActiveTabColor {
            get {
                return ((string)(this["DarkModeActiveTabColor"]));
            }
            set {
                this["DarkModeActiveTabColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF303030")]
        public string DarkModeInactiveTabColor {
            get {
                return ((string)(this["DarkModeInactiveTabColor"]));
            }
            set {
                this["DarkModeInactiveTabColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string LightModeActiveTabColor {
            get {
                return ((string)(this["LightModeActiveTabColor"]));
            }
            set {
                this["LightModeActiveTabColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F0F0")]
        public string LightModeInactiveTabColor {
            get {
                return ((string)(this["LightModeInactiveTabColor"]));
            }
            set {
                this["LightModeInactiveTabColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JellyfinNavigationOrder {
            get {
                return ((string)(this["JellyfinNavigationOrder"]));
            }
            set {
                this["JellyfinNavigationOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubsonicNavigationOrder {
            get {
                return ((string)(this["SubsonicNavigationOrder"]));
            }
            set {
                this["SubsonicNavigationOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF303030")]
        public string DarkModeMediaControlsColor {
            get {
                return ((string)(this["DarkModeMediaControlsColor"]));
            }
            set {
                this["DarkModeMediaControlsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F0F0")]
        public string LightModeMediaControlsColor {
            get {
                return ((string)(this["LightModeMediaControlsColor"]));
            }
            set {
                this["LightModeMediaControlsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string LightModeTextColor {
            get {
                return ((string)(this["LightModeTextColor"]));
            }
            set {
                this["LightModeTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string DarkModeTextColor {
            get {
                return ((string)(this["DarkModeTextColor"]));
            }
            set {
                this["DarkModeTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CAF50")]
        public string LightModeForwardReverseColor {
            get {
                return ((string)(this["LightModeForwardReverseColor"]));
            }
            set {
                this["LightModeForwardReverseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CAF50")]
        public string LightModeShuffleColor {
            get {
                return ((string)(this["LightModeShuffleColor"]));
            }
            set {
                this["LightModeShuffleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#81C784")]
        public string DarkModeForwardReverseColor {
            get {
                return ((string)(this["DarkModeForwardReverseColor"]));
            }
            set {
                this["DarkModeForwardReverseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#81C784")]
        public string DarkModeShuffleColor {
            get {
                return ((string)(this["DarkModeShuffleColor"]));
            }
            set {
                this["DarkModeShuffleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CachedJellyfinLibraries {
            get {
                return ((string)(this["CachedJellyfinLibraries"]));
            }
            set {
                this["CachedJellyfinLibraries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CachedJellyfinItems {
            get {
                return ((string)(this["CachedJellyfinItems"]));
            }
            set {
                this["CachedJellyfinItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAIApiKey {
            get {
                return ((string)(this["OpenAIApiKey"]));
            }
            set {
                this["OpenAIApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnthropicApiKey {
            get {
                return ((string)(this["AnthropicApiKey"]));
            }
            set {
                this["AnthropicApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11434")]
        public string OllamaUrl {
            get {
                return ((string)(this["OllamaUrl"]));
            }
            set {
                this["OllamaUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("llama2")]
        public string OllamaModel {
            get {
                return ((string)(this["OllamaModel"]));
            }
            set {
                this["OllamaModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableOpenAI {
            get {
                return ((bool)(this["EnableOpenAI"]));
            }
            set {
                this["EnableOpenAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAnthropic {
            get {
                return ((bool)(this["EnableAnthropic"]));
            }
            set {
                this["EnableAnthropic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableOllama {
            get {
                return ((bool)(this["EnableOllama"]));
            }
            set {
                this["EnableOllama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public double LastVolume {
            get {
                return ((double)(this["LastVolume"]));
            }
            set {
                this["LastVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RssServerUrl {
            get {
                return ((string)(this["RssServerUrl"]));
            }
            set {
                this["RssServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RssUsername {
            get {
                return ((string)(this["RssUsername"]));
            }
            set {
                this["RssUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RssPassword {
            get {
                return ((string)(this["RssPassword"]));
            }
            set {
                this["RssPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public bool RssAutoMarkAsRead {
            get {
                return ((bool)(this["RssAutoMarkAsRead"]));
            }
            set {
                this["RssAutoMarkAsRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("List")]
        public string RssReadingMode {
            get {
                return ((string)(this["RssReadingMode"]));
            }
            set {
                this["RssReadingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RssTabOpen {
            get {
                return ((bool)(this["RssTabOpen"]));
            }
            set {
                this["RssTabOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExpandedPaths {
            get {
                return ((string)(this["ExpandedPaths"]));
            }
            set {
                this["ExpandedPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WeatherZipCode {
            get {
                return ((string)(this["WeatherZipCode"]));
            }
            set {
                this["WeatherZipCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableWeather {
            get {
                return ((bool)(this["EnableWeather"]));
            }
            set {
                this["EnableWeather"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMoonPhase {
            get {
                return ((bool)(this["EnableMoonPhase"]));
            }
            set {
                this["EnableMoonPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WeatherApiKey {
            get {
                return ((string)(this["WeatherApiKey"]));
            }
            set {
                this["WeatherApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XAIApiKey {
            get {
                return ((string)(this["XAIApiKey"]));
            }
            set {
                this["XAIApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableXAI {
            get {
                return ((bool)(this["EnableXAI"]));
            }
            set {
                this["EnableXAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UniversaWebUrl {
            get {
                return ((string)(this["UniversaWebUrl"]));
            }
            set {
                this["UniversaWebUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UniversaWebUsername {
            get {
                return ((string)(this["UniversaWebUsername"]));
            }
            set {
                this["UniversaWebUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UniversaWebPassword {
            get {
                return ((string)(this["UniversaWebPassword"]));
            }
            set {
                this["UniversaWebPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableWebSync {
            get {
                return ((bool)(this["EnableWebSync"]));
            }
            set {
                this["EnableWebSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSync {
            get {
                return ((bool)(this["AutoSync"]));
            }
            set {
                this["AutoSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SyncServerUrl {
            get {
                return ((string)(this["SyncServerUrl"]));
            }
            set {
                this["SyncServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SyncUsername {
            get {
                return ((string)(this["SyncUsername"]));
            }
            set {
                this["SyncUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SyncPassword {
            get {
                return ((string)(this["SyncPassword"]));
            }
            set {
                this["SyncPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SyncIntervalMinutes {
            get {
                return ((int)(this["SyncIntervalMinutes"]));
            }
            set {
                this["SyncIntervalMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/1/0001")]
        public global::System.DateTime LastWebSyncTime {
            get {
                return ((global::System.DateTime)(this["LastWebSyncTime"]));
            }
            set {
                this["LastWebSyncTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAICharacterization {
            get {
                return ((bool)(this["EnableAICharacterization"]));
            }
            set {
                this["EnableAICharacterization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAIChat {
            get {
                return ((bool)(this["EnableAIChat"]));
            }
            set {
                this["EnableAIChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsChatExpanded {
            get {
                return ((bool)(this["IsChatExpanded"]));
            }
            set {
                this["IsChatExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixServerUrl {
            get {
                return ((string)(this["MatrixServerUrl"]));
            }
            set {
                this["MatrixServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatrixServiceName {
            get {
                return ((string)(this["MatrixServiceName"]));
            }
            set {
                this["MatrixServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsLibraryExpanded {
            get {
                return ((bool)(this["IsLibraryExpanded"]));
            }
            set {
                this["IsLibraryExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseBetaChains {
            get {
                return ((bool)(this["UseBetaChains"]));
            }
            set {
                this["UseBetaChains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebDavServerUrl {
            get {
                return ((string)(this["WebDavServerUrl"]));
            }
            set {
                this["WebDavServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebDavUsername {
            get {
                return ((string)(this["WebDavUsername"]));
            }
            set {
                this["WebDavUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebDavPassword {
            get {
                return ((string)(this["WebDavPassword"]));
            }
            set {
                this["WebDavPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebDavRemoteFolder {
            get {
                return ((string)(this["WebDavRemoteFolder"]));
            }
            set {
                this["WebDavRemoteFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WebDavAutoSync {
            get {
                return ((bool)(this["WebDavAutoSync"]));
            }
            set {
                this["WebDavAutoSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int WebDavSyncIntervalMinutes {
            get {
                return ((int)(this["WebDavSyncIntervalMinutes"]));
            }
            set {
                this["WebDavSyncIntervalMinutes"] = value;
            }
        }
    }
}
