name: Build .NET Desktop App

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag that starts with 'v'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Adjust this to match your project's .NET version
        
    - name: Restore dependencies
      run: dotnet restore Universa.Desktop/Universa.Desktop.csproj
      
    - name: Build
      run: dotnet build Universa.Desktop/Universa.Desktop.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test Universa.Desktop/Universa.Desktop.csproj --configuration Release --no-build
      
    - name: Publish
      run: dotnet publish Universa.Desktop/Universa.Desktop.csproj --configuration Release --no-build --output ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Universa-Desktop-App
        path: ./publish
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./publish/**
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 