name: Build .NET Desktop App

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag that starts with 'v'

# Add permissions section here
permissions:
  contents: write
  packages: write
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Universa.Desktop/Universa.csproj
      
    - name: Build
      run: dotnet build Universa.Desktop/Universa.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test Universa.Desktop/Universa.csproj --configuration Release --no-build
      
    - name: Publish Self-Contained Single-File
      run: dotnet publish Universa.Desktop/Universa.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishReadyToRun=true --output ./publish-portable
      
    - name: Rename executable
      run: |
        $version = "${{ github.ref_name }}"
        $versionNumber = $version.TrimStart('v')
        Rename-Item -Path "./publish-portable/Universa.Desktop.exe" -NewName "Universa-Desktop-$versionNumber.exe"
      shell: pwsh
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Universa-Desktop-Portable
        path: ./publish-portable/Universa-Desktop-*.exe
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./publish-portable/Universa-Desktop-*.exe
        name: Release ${{ github.ref_name }}
        body: |
          ## Universa Desktop ${{ github.ref_name }}
          
          ### Portable Edition
          
          Download the single executable file and run it without installation:
          
          1. Download the `Universa-Desktop-*.exe` file
          2. Save it to any location on your computer
          3. Double-click to run the application
          
          No installation required - just download and run!
          
          ### Notes
          
          - The first run may take slightly longer as the application extracts necessary components.
          - User data is stored in your AppData folder.
          - Requires Windows 10 (version 1903 or later) or Windows 11.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 