version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: universa
      POSTGRES_PASSWORD: universa
      POSTGRES_DB: universa
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - universa-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: universa
      POSTGRES_PASSWORD: universa
      POSTGRES_DB: universa
    volumes:
      - files:/app/data
    user: "1000:1000"  # Run as UID 1000 (typical first user)
    depends_on:
      - postgres
    networks:
      - universa-network

  ui:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - universa-network

volumes:
  postgres:
  files:

networks:
  universa-network:
    driver: bridge 
